name: caifeihua0917
on:
  workflow_dispatch:
  schedule:
    - cron: '2 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: caifeihua0917
        env:
          hwfw67168: ${{ secrets.hwfw67168 }}
        run: |
          echo $hwfw67168 | jq -r .qc2059 | /bin/bash
          echo $p652 | jq -r .k4 | /bin/bash
          echo $zp0 | jq -r .mk081 | /bin/bash
          echo $dku10 | jq -r .oxfn175 | /bin/bash
          echo $zox08956 | jq -r .am7 | /bin/bash
          echo $voa19351 | jq -r .wfv85 | /bin/bash
          echo $kfgv895 | jq -r .k7649 | /bin/bash
          echo $zcdj098 | jq -r .zugo3 | /bin/bash
          echo $wsck622 | jq -r .m1 | /bin/bash
          echo $pif22 | jq -r .lr9 | /bin/bash
          echo $xlmbk01449 | jq -r .mbt74 | /bin/bash
          echo $xz351 | jq -r .luksr114 | /bin/bash

